export const FETCH_CHEAPEST_DEALS_BEGIN  = 'FETCH_CHEAPEST_DEALS_BEGIN';
export const FETCH_CHEAPEST_DEALS_SUCCESS = 'FETCH_CHEAPEST_DEALS_SUCCESS';
export const FETCH_CHEAPEST_DEALS_FAILED = 'FETCH_CHEAPEST_DEALS_FAILED';